apiVersion: apps/v1
kind: Deployment
metadata:
  name: addons-jaeger-query
  namespace: istio-system
spec:
  template:
    spec:
      containers:
      - name: keycloak-gatekeeper
        image: quay.io/keycloak/keycloak-gatekeeper:10.0.0
        args:
          - --config=/etc/gatekeeper-config/jaeger.yaml
        ports:
          - containerPort: 8000
            name: gatekeeper-http
        volumeMounts:
          - name: gatekeeper-config
            mountPath: /etc/gatekeeper-config/
      volumes:
        - name: gatekeeper-config
          configMap:
            name: addons-oidc-gatekeeper-config
