resources:
- .addons-install-pre.yaml

patchesStrategicMerge:
- jaeger.deploy.yaml
- jaeger.svc.yaml
- kiali.deploy.yaml
- kiali.svc.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: addons-oidc-gatekeeper-config
  namespace: istio-system
  files:
  - configmap/kiali.yaml
  - configmap/jaeger.yaml