redirection-url: http://kiali.qcloud.jijiechen.com
discovery-url: https://keycloak.qcloud.jijiechen.com/auth/realms/master
upstream-url: http://127.0.0.1:20001/
skip-openid-provider-tls-verify: true
client-id: kiali-client
client-secret: e767c153-3c1c-414a-908f-bb4fefc7669f
enable-refresh-tokens: true
listen: :8000
secure-cookie: false
# listen: :8443
tls-cert: 
tls-private-key: 
encryption-key: nkOfcT6jYCsXFuV5YRkt3OvY9dy1c0ck
resources:
  - uri: /*
    groups:
      - kiali_users
