redirection-url: http://jaeger.WILDCARD_BASE_DOMAIN
discovery-url: https://keycloak.WILDCARD_BASE_DOMAIN/auth/realms/mesh
upstream-url: http://127.0.0.1:16686/
skip-openid-provider-tls-verify: true
client-id: jaeger-client
client-secret: JJJJJJJJ
enable-refresh-tokens: true
listen: :8000
secure-cookie: false
# listen: :8443
tls-cert: 
tls-private-key: 
encryption-key: nkOfcT6jYCsXFuV5YRkt3OvY9dy1c0ck
resources:
  - uri: /*
    groups:
      - jaeger_users
