redirection-url: http://kiali.WILDCARD_BASE_DOMAIN
discovery-url: https://keycloak.WILDCARD_BASE_DOMAIN/auth/realms/master
upstream-url: http://127.0.0.1:20001/
skip-openid-provider-tls-verify: true
client-id: kiali-client
client-secret: AAAAAAAA
enable-refresh-tokens: true
listen: :8000
secure-cookie: false
# listen: :8443
tls-cert: 
tls-private-key: 
encryption-key: nkOfcT6jYCsXFuV5YRkt3OvY9dy1c0ck
resources:
  - uri: /*
    groups:
      - kiali_users
