resources:
- .addons-install-pre.yaml

patchesStrategicMerge:
- deploy.kiali.yaml
- deploy.jaeger.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: addons-oidc-gatekeeper-config
  namespace: istio-system
  files:
  - configmap/kiali.yaml
  - configmap/jaeger.yaml